package:
  name: sample_project
  version: 1.0

source:
  git_url: https://github.com/syne-navneet/sample_project.git

build:
  number: 1

requirements: 
  build:
    #- python
    #- setuptools

  run:
    #- python
 
  #always_include_files:
  #  - work/sample/testfile.py
