package:
  name: sample_project
  version: 0.1

source:
  path: ../sample_project

build:
  string: py3.7
  preserve_egg_dir: True

requirements: 
  build:
    #- python
    #- setuptools

  run:
    #- python

#test:
#  imports:
#    - sample_project 
