package:
  name: sample_project
  version: 0.1

source:
  path: ../sample_project

build:
  string: py3.7

requirements: 
  build:
    - python
    - setuptools

  run:
    - python

test:
  requires:
    - pytest
